"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.supabase = void 0;
// This file is automatically generated. Do not edit it directly.
const supabase_js_1 = require("@supabase/supabase-js");
const SUPABASE_URL = "https://demcjskpwcxqohzlyjxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbWNqc2twd2N4cW9oemx5anhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDIxMzUsImV4cCI6MjA3MDYxODEzNX0.9p5j5yUKF-HAJCuo8A2BqNhB8JVV9Sgc2KdekRuR4Ww";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
exports.supabase = (0, supabase_js_1.createClient)(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        // During server-side builds (Next.js) `localStorage` and `window` are not available.
        // Use a minimal no-op storage implementation to avoid ReferenceError during SSR.
        storage: (typeof window !== 'undefined' && typeof localStorage !== 'undefined')
            ? localStorage
            : {
                length: 0,
                clear: () => { },
                getItem: (_key) => null,
                key: (_index) => null,
                removeItem: (_key) => { },
                setItem: (_key, _value) => { },
            },
        persistSession: true,
        autoRefreshToken: true,
    }
});
