// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://demcjskpwcxqohzlyjxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbWNqc2twd2N4cW9oemx5anhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDIxMzUsImV4cCI6MjA3MDYxODEzNX0.9p5j5yUKF-HAJCuo8A2BqNhB8JVV9Sgc2KdekRuR4Ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// During server-side builds (Next.js) `localStorage` and `window` are not available.
// Provide a minimal no-op storage implementation to avoid ReferenceError during SSR
const safeStorage: Storage = (typeof window !== 'undefined' && typeof localStorage !== 'undefined')
  ? localStorage
  : {
      length: 0,
      clear() {},
      getItem(_key: string) { return null; },
      key(_index: number) { return null; },
      removeItem(_key: string) {},
      setItem(_key: string, _value: string) {},
    } as unknown as Storage;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});