-- Inserir um usuário de teste para o broker
INSERT INTO auth.users (id, email, email_confirmed_at, created_at, updated_at, raw_user_meta_data, instance_id)
VALUES (
    gen_random_uuid(),
    'teste@imobiliaria.com',
    now(),
    now(),
    now(),
    '{"nome": "Admin Teste", "email": "teste@imobiliaria.com"}',
    '00000000-0000-0000-0000-000000000000'
);

-- Inserir um broker de teste
INSERT INTO brokers (
    id,
    user_id,
    business_name,
    website_slug,
    email,
    phone,
    address,
    city,
    uf,
    cep,
    logo_url,
    primary_color,
    secondary_color,
    is_active,
    subscription_status,
    subscription_tier,
    site_title,
    site_description,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    (SELECT id FROM auth.users WHERE email = 'teste@imobiliaria.com' LIMIT 1),
    'Imobiliária Teste',
    'imobiliaria-teste',
    'teste@imobiliaria.com',
    '(11) 99999-9999',
    'Rua das Flores, 123',
    'São Paulo',
    'SP',
    '01234-567',
    '/placeholder.svg',
    '#2563eb',
    '#64748b',
    true,
    'active',
    'pro',
    'Imobiliária Teste - Os Melhores Imóveis',
    'Encontre o imóvel dos seus sonhos com a Imobiliária Teste. Oferecemos as melhores opções de casas, apartamentos e terrenos.',
    now(),
    now()
);

-- Inserir algumas propriedades de teste
INSERT INTO properties (
    id,
    broker_id,
    title,
    description,
    price,
    property_type,
    transaction_type,
    address,
    neighborhood,
    city,
    uf,
    bedrooms,
    bathrooms,
    area_m2,
    parking_spaces,
    is_featured,
    is_active,
    main_image_url,
    images,
    features,
    status,
    slug,
    created_at,
    updated_at
) VALUES 
(
    gen_random_uuid(),
    (SELECT id FROM brokers WHERE website_slug = 'imobiliaria-teste' LIMIT 1),
    'Apartamento Moderno Centro',
    'Lindo apartamento no centro da cidade, totalmente reformado com acabamentos de primeira qualidade.',
    450000,
    'Apartamento',
    'Venda',
    'Rua Central, 456',
    'Centro',
    'São Paulo',
    'SP',
    3,
    2,
    85,
    1,
    true,
    true,
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80"]',
    '["Varanda", "Churrasqueira", "Piscina"]',
    'available',
    'apartamento-moderno-centro',
    now(),
    now()
),
(
    gen_random_uuid(),
    (SELECT id FROM brokers WHERE website_slug = 'imobiliaria-teste' LIMIT 1),
    'Casa Familiar Jardins',
    'Ampla casa familiar em condomínio fechado, com área de lazer completa e segurança 24h.',
    750000,
    'Casa',
    'Venda',
    'Rua das Palmeiras, 789',
    'Jardins',
    'São Paulo',
    'SP',
    4,
    3,
    150,
    2,
    true,
    true,
    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
    '["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80", "https://images.unsplash.com/photo-1493663284031-b7e3aaa4cab7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80"]',
    '["Área de lazer", "Piscina", "Academia", "Segurança 24h"]',
    'available',
    'casa-familiar-jardins',
    now(),
    now()
);