name: adminimobiliaria
region: nyc

services:
  # Frontend Next.js (standalone - sem backend separado)
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: dani1964-creator/danierickgithub
    source_dir: /frontend
    build_command: npm install && npm run build
    run_command: ./start.sh
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_PUBLIC_DOMAIN
        scope: RUN_AND_BUILD_TIME
        value: ${NEXT_PUBLIC_BASE_PUBLIC_DOMAIN}
      - key: NEXT_PUBLIC_APP_URL
        scope: RUN_AND_BUILD_TIME
        value: ${NEXT_PUBLIC_APP_URL}
      - key: NEXT_PUBLIC_CNAME_TARGET
        scope: RUN_AND_BUILD_TIME
        value: ${NEXT_PUBLIC_CNAME_TARGET}
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${NEXT_PUBLIC_SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: SUPABASE_URL
        scope: RUN_TIME
        value: ${SUPABASE_URL}
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        value: ${SUPABASE_SERVICE_ROLE_KEY}
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

# Configurações globais
features:
  - buildpack-stack=ubuntu-22